{% set data = load_setup_py_data() %}

package:
  name: bmi-tester
  version: {{ data.get('version') }}

source:
  path: ..

requirements:
  build:
    - python
    - setuptools
    - numpydoc
    - nose
    - numpy
    - cfunits-python
    - standard_names

  run:
    - python
    - setuptools
    - numpydoc
    - nose
    - numpy
    - cfunits-python
    - standard_names

build:
  number: 0
  entry_points:
    - bmi-tester=bmi_tester.cmd:main
    - bmi-nose=bmi_tester.bminose:main
  script: python setup.py install --single-version-externally-managed --record record.txt

test:
  imports:
    - bmi_tester
  commands:
    - bmi-tester -h
    - bmi-nose -h

about:
  home: http://github.com/csdms/bmi-tester
  license: MIT
  summary: Test BMI implementation in Python
  doc_url: http://bmi-tester.readthedocs.io/en/latest/
  dev_url: http://github.com/csdms/bmi-tester
