{% set data = load_setup_py_data() %}

package:
  name: bmi-tester
  version: {{ data.get('version') }}

source:
  path: ..

requirements:
  build:
    - python
    - pip

  run:
    - python
    - numpy
    - pytest
    - scripting
    - cfunits
    - standard_names
    - model_metadata
    - click

build:
  number: 0
  entry_points:
    - bmi-test=bmi_tester.bmipytest:main
  script: python -m pip install --no-deps --ignore-installed .

test:
  imports:
    - bmi_tester
  commands:
    - bmi-test --help

about:
  home: http://github.com/csdms/bmi-tester
  license: MIT
  summary: Test BMI implementation in Python
  doc_url: http://bmi-tester.readthedocs.io/en/latest/
  dev_url: http://github.com/csdms/bmi-tester
