language: generic
os:
- linux
- osx
env:
  matrix:
  - CONDA_ENV=py36
  - CONDA_ENV=py37
  - CONDA_ENV=lint
matrix:
  exclude:
  - os: osx
    env: CONDA_ENV=lint
sudo: false
jobs:
  include:
  - stage: deploy
    if: tag =~ v.*$
    script: skip
    os: linux
    deploy:
      on:
        all_branches: true
      provider: pypi
      user: mcflugen
      password: 
        secure: Hs2d1XF71m6JzYIPFYq51hMmpV2x+fik6Q/0UN2yx+Me+rLGxSJEmw26q+3+rkg+bLsmHgdt88z+uuwqYEatRBwlK8zPMDew8cFe6cEJFqdECuABh5LxL3x+LsbXInvIzIlRkavIO6tdksbM6GU07koYA8C1p9ozrzUhhYxbVj5F3ULh0Bso8kGzokjLOXKTxhY7sXQoeNHn+McyG9PGXkH0Z2ZIRXWIJOZKrUAugAZRe+tXBsBXP6nu3XMsrymD9bxHMno5u7Y7/ZKOOzHiE6pyBZaLke/WX4frTShOMxAXGS6yziIvKK0tiYPAIi4MYDxLIrf1UVYk7qz5lxyd36R4gzXooluG+1EgbIWqD+xFQKeOQKwKUZB0byyI0LwiG/buvJSeJw3tIpoe61SYsJQfoUswq4SymqO+EAuTbne8dotTTtoJdaevZewCiowg32EOnHK74peoa492Q+lAXE/NsoDgJOMSJp4C9GMfTiv10QuQ2hHaccxevtuEriNiMlt3A+PARe5ctW+ZWDnamj4dh/kMG2N3oyyTghaaC7HXSP5YZDaTP0xF+eXp32oC76KmdxeB1UFTE60TQhK1PbYp7CwrwaZyoM45dmqGJ8Hc88W+YtyK2O3jA6t6dKWxLo2v3FskGUhHSrOZJNSG9zY7luH5Q6d2tU8drfmhY/g=
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > $HOME/miniconda.sh
  else
    curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh > $HOME/miniconda.sh
  fi
- bash $HOME/miniconda.sh -b -p $HOME/anaconda
- export PATH="$HOME/anaconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- |
  if [[ "$CONDA_ENV" == "docs" ]]; then
    conda env create -n test_env --file docs/environment.yml
  else
    conda env create -n test_env --file ci/requirements-$CONDA_ENV-$TRAVIS_OS_NAME.yml
  fi
- source activate test_env
- pip install . -r requirements.txt
script:
- |
  if [[ "$CONDA_ENV" == "lint" ]]; then
    make lint
  elif [[ "$CONDA_ENV" == "docs" ]]; then
    sphinx-apidoc --force -o docs/api bmi_tester *tests
    make -C docs clean html
  else
    pytest --cov=bmi_tester --cov-report=xml:$(pwd)/coverage.xml -vvv
  fi
after_success: coveralls
