language: generic
os:
- linux
- osx
env:
  matrix:
  - TRAVIS_PYTHON_VERSION="2.7"
  - TRAVIS_PYTHON_VERSION="3.5"
  - TRAVIS_PYTHON_VERSION="3.6"
  - TRAVIS_PYTHON_VERSION="3.7"
  global:
  - CONDA_PREFIX=$HOME/miniconda
  - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda3-latest"
  - secure: HCgc/kDB6aAvjc3emPHuAM+dLQLW6s52oiPSTrf05Y7NV2F+CPmo+08GBP0rJNZPukZtsPF/ONYKdgi5Ran9k2SFeDASzWHMGBNIsE4ialBBB7k6qkJcqQQEPIWk9uwndUI+OUMCOQuz8cFfZczRW54oH96qx2kt9klsc7hFFrH9KB8e/ZkpGeAgabnQyFctkFXsrDaJdrqbkO+ATFhCTNPN83ILQn8BEKw5iSWfhNl4LAvCbSeMBF80mYJ64K/ZHuPszszFXpt09pce0+XXzfiNmzPzzw9eRKTG4dV7spanZOt+UkjSwUi7DJPBCEAKVPyxMYfkslM/t4hJRDq3WXkMBRZNnsp9bud8ZPBDymxwdziX89fiY6uNzjtCS2y2nX4fdWVUyBtpjed8AqcJFm9Fz8ejbzVYSlMxkAj3mJ+ki1ZdQUm24kaJ2Y8EWpeOjOtfJAjri+iVnNgY4pdM0JhNMhP/4R7/nJw1meYZs4PAIgYy0snbggFyG0H8kV8EVysJ3Qe21Qkdi+ov+GXmyw7by7++zWmJ4ldbcn61xmsEWgBhj7/X4/uWHuNHXqW/uzs3XkQfOnIsFIEgfq8oO8ljgv0U4wmImHk7WxmWHgU2lPM2r8tBYNzeE9KpvYgZEyiOgkauzkKHrlCSNzJEpb30BOmQBFdRsAPCeBhDx/M=
sudo: false
before_install:
- |
  if [[ $TRAVIS_OS_NAME == "osx" ]]; then
    brew remove --force $(brew list)
    brew cleanup -s
    rm -rf $(brew --cache)
  fi
install:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    OS="MacOSX-x86_64"
  else
    OS="Linux-x86_64"
  fi
- curl $MINICONDA_URL_BASE-$OS.sh > $HOME/minconda.sh
- bash $HOME/minconda.sh -b -p $CONDA_PREFIX
- export PATH="$CONDA_PREFIX/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda config --add channels conda-forge
- conda create -n _testing python=$TRAVIS_PYTHON_VERSION
- source activate _testing
- conda install -q conda-build anaconda-client sphinx pytest flake8
- conda install -q --file=requirements.txt
script:
- make lint test
- conda build ./conda-recipe --old-build-string
after_success:
- curl https://raw.githubusercontent.com/csdms/ci-tools/master/anaconda_upload.py
  > $HOME/anaconda_upload.py
- echo $ANACONDA_TOKEN | python $HOME/anaconda_upload.py ./recipe --channel=main --org=csdms
  --old-build-string --token=-
