name: Test

on: [push, pull_request]

jobs:
  build-and-test:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true

      - name: Show conda installation info
        run: |
          mamba info
          mamba list

      - name: Build and install package
        run: |
          make install

      - name: Test
        run: |
          python -c 'import bmi_tester; print(bmi_tester.__version__)'
          pytest --cov=bmi_tester --cov-report=xml:$(pwd)/coverage.xml -vvv

      - name: Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        uses: AndreMiras/coveralls-python-action@develop
